import logo from './logo.png';
import bg from './bg.png';
import li1 from './li1.png';
import li2 from './li2.png';
import li3 from './li3.png';
import li4 from './li4.png';
import leadbanner from './leadbanner.png';
import leadgrowth from './leadgrowth.png';
import leads from './leads.png';
import leadtrusted from './leadtrusted.png';
import work from './work.png';
import t1 from './t1.png';
import t2 from './t2.png';
import t3 from './t3.png';
import testimonal1 from './testimonal1.png';
import testimonal2 from './testimonal2.png';
import tr1 from './tr1.png';
import tr2 from './tr2.png';
import tr3 from './tr3.png';
import youtube from './youtube.png';
import utube from './utube.png';
import facebook from './facebook.png';
import google from './google.png';
import trustpilot from './trustpilot.png';
import p1 from './p1.png';
import p2 from './p2.png';
import p3 from './p3.png';
import p4 from './p4.png';
import p5 from './p5.png';
import p6 from './p6.png';
import p7 from './p7.png';
import p8 from './p8.png';
import article1 from './article1.png';
import article2 from './article2.png';
import contactus from './contactus.png';

export { logo, bg, li1, li2, li3, li4, leadbanner, leadgrowth, leads, leadtrusted, work, t1, t2, t3, testimonal1, testimonal2, tr1, tr2, tr3, youtube, utube, facebook, google, trustpilot, p1, p2, p3, p4, p5, p6, p7, p8, article1, article2, contactus };

